org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

minecraft_version=1.21.1
neoforge_version=21.1.169
parchment_mc_version=1.21.1
parchment_mapping_version=2024.11.17

mod_id=enchantpredict
mod_name=Enchantment Prediction
mod_version=1.0.0
mod_group=net.earthcomputer.enchantpredict

seedfinding_core_version=1.210.0
seedfinding_biome_version=1.171.1
seedfinding_feature_version=1.171.11
seedfinding_seed_version=1.171.2
latticg_version=1.07
